### ISSUE TITLE
UX Epic

### ISSUE THREAD

**Issue by g-a-v-i-n** [g-a-v-i-n/svg-filter-lab#3]
- [ ] Checkmarks don't appear in `<Select />` on default values
- [ ] Edge hover area is too thin
- [ ] Draggable edge is not styled
- [ ] `<NodeMatrixInput/>` needs optional x and y axis labels
